car_models = {
    "Acura": ["Integra", "TLX", "MDX", "RDX", "NSX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
    "Aston Martin": ["DB11", "Vantage", "DBS", "Valhalla", "DBX"],
    "Audi": ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "TT", "R8", "e-tron"],
    "Bentley": ["Continental", "Flying Spur", "Bentayga", "Mulsanne"],
    "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "i7", "iX"],
    "Bugatti": ["Chiron", "Divo", "La Voiture Noire", "Centodieci", "Bolide"],
    "Buick": ["Encore", "Encore GX", "Envision", "LaCrosse", "Regal"],
    "Cadillac": ["CT4", "CT5", "CT6", "XT4", "XT5", "XT6", "Escalade"],
    "Chevrolet": ["Camaro", "Corvette", "Malibu", "Impala", "Silverado", "Tahoe", "Suburban", "Equinox", "Traverse", "Bolt", "Spark"],
    "Chrysler": ["300", "Pacifica"],
    "Dodge": ["Challenger", "Charger", "Durango", "Hornet"],
    "Ferrari": ["296", "F8", "SF90", "Roma", "Portofino", "LaFerrari"],
    "Fiat": ["500", "500X", "Tipo"],  # Limited models in some markets
    "Ford": ["Mustang", "F-150", "Super Duty", "Explorer", "Escape", "Edge", "Bronco", "Maverick", "Focus", "Fusion", "Mach-E"],
    "Genesis": ["G70", "G80", "G90", "GV70", "GV80"],
    "GMC": ["Sierra", "Canyon", "Yukon", "Acadia", "Terrain"],
    "Honda": ["Civic", "Accord", "CR-V", "Pilot", "Odyssey", "Ridgeline", "HR-V", "Passport", "Insight"],
    "Hyundai": ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Kona", "Venue", "Accent"],
    "Infiniti": ["Q50", "Q60", "Q70", "QX50", "QX60", "QX80"],
    "Jaguar": ["XE", "XF", "XJ", "F-Pace", "I-Pace", "E-Pace"],
    "Jeep": ["Wrangler", "Grand Cherokee", "Cherokee", "Gladiator", "Renegade", "Compass"],
    "Kia": ["Forte", "Optima", "K5", "Sportage", "Sorento", "Telluride", "Soul", "Niro", "Rio"],
    "Lamborghini": ["Huracan", "Aventador", "Urus", "Revuelto"],
    "Land Rover": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Discovery", "Defender", "Evoque"],
    "Lexus": ["IS", "ES", "LS", "GS", "LC", "RC", "NX", "RX", "LX", "GX"],
    "Lincoln": ["Navigator", "Aviator", "Corsair", "Nautilus"],
    "Lotus": ["Emira", "Evija"],  # Limited models
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "MC20"],
    "Mazda": ["Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-50", "CX-9", "MX-5 Miata"],
    "McLaren": ["720S", "765LT", "Artura", "GT"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "G-Class", "GLA", "GLC", "GLE", "GLS", "CLA", "CLB", "CLS", "AMG GT"],
    "Mini": ["Cooper", "Clubman", "Countryman"],
    "Mitsubishi": ["Outlander", "Eclipse Cross", "Mirage"],
    "Nissan": ["Altima", "Sentra", "Maxima", "Leaf", "Rogue", "Murano", "Pathfinder", "Titan", "Armada", "Z"],
    "Porsche": ["911", "718", "Taycan", "Panamera", "Macan", "Cayenne"],
    "Ram": ["1500", "2500", "3500", "Promaster"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan"],
    "Subaru": ["Impreza", "Crosstrek", "Forester", "Outback", "Legacy", "WRX", "BRZ", "Ascent"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck"],
    "Toyota": ["Corolla", "Camry", "Avalon", "Prius", "RAV4", "Highlander", "4Runner", "Tacoma", "Tundra", "Land Cruiser", "GR86", "Supra"],
    "Volkswagen": ["Jetta", "Golf", "Passat", "Arteon", "Tiguan", "Atlas", "Taos"],
    "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
    # ... Add more brands as needed
}

